// apps/anarabottini/src/components/Modal.tsx
import { useEffect, useRef, type ReactNode } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, ChevronLeft, ChevronRight } from 'lucide-react';
import { cn } from '../lib/utils';

type ModalProps = {
  open: boolean;
  onClose: () => void;
  children: ReactNode;
  label?: string;
  onPrev?: () => void;
  onNext?: () => void;
  size?: 'lg' | 'xl';
  className?: string;
};

/**
 * Modal genérico (base de PalestraModal e VideoLightbox). Extrai a mecânica do
 * lightbox do rmambiental: AnimatePresence, trava de scroll do body, Esc/setas,
 * clique no backdrop e botão de fechar. Acessível (role=dialog, foco inicial).
 */
export default function Modal({ open, onClose, children, label, onPrev, onNext, size = 'lg', className }: ModalProps) {
  const panelRef = useRef<HTMLDivElement>(null);
  // Callbacks via ref para o efeito depender só de `open` (evita re-disparo a cada render).
  const cb = useRef({ onClose, onPrev, onNext });
  cb.current = { onClose, onPrev, onNext };

  useEffect(() => {
    if (!open) return;
    const prevFocused = document.activeElement as HTMLElement | null;

    const focusables = () =>
      Array.from(
        panelRef.current?.querySelectorAll<HTMLElement>(
          'a[href], button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])',
        ) ?? [],
      ).filter((el) => el.offsetParent !== null);

    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') return cb.current.onClose();
      if (e.key === 'ArrowLeft') return cb.current.onPrev?.();
      if (e.key === 'ArrowRight') return cb.current.onNext?.();
      if (e.key === 'Tab') {
        const f = focusables();
        if (f.length === 0) {
          e.preventDefault();
          panelRef.current?.focus();
          return;
        }
        const first = f[0];
        const last = f[f.length - 1];
        const active = document.activeElement;
        if (e.shiftKey && (active === first || active === panelRef.current)) {
          e.preventDefault();
          last.focus();
        } else if (!e.shiftKey && active === last) {
          e.preventDefault();
          first.focus();
        }
      }
    };

    window.addEventListener('keydown', onKey);
    document.body.style.overflow = 'hidden';
    const t = setTimeout(() => panelRef.current?.focus(), 30);
    return () => {
      window.removeEventListener('keydown', onKey);
      document.body.style.overflow = '';
      clearTimeout(t);
      prevFocused?.focus?.(); // devolve o foco ao elemento que abriu o modal
    };
  }, [open]);

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          className="fixed inset-0 z-[70] flex items-center justify-center p-4 sm:p-6"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.2 }}
        >
          <div className="absolute inset-0 bg-brand-ink/70 backdrop-blur-sm" onClick={onClose} aria-hidden />

          {onPrev && (
            <button
              onClick={onPrev}
              aria-label="Anterior"
              className="absolute left-3 top-1/2 z-10 grid h-11 w-11 -translate-y-1/2 place-items-center rounded-full bg-white/90 text-brand-ink shadow-soft transition-transform hover:scale-105 sm:left-6"
            >
              <ChevronLeft className="h-5 w-5" />
            </button>
          )}
          {onNext && (
            <button
              onClick={onNext}
              aria-label="Próximo"
              className="absolute right-3 top-1/2 z-10 grid h-11 w-11 -translate-y-1/2 place-items-center rounded-full bg-white/90 text-brand-ink shadow-soft transition-transform hover:scale-105 sm:right-6"
            >
              <ChevronRight className="h-5 w-5" />
            </button>
          )}

          <motion.div
            ref={panelRef}
            tabIndex={-1}
            role="dialog"
            aria-modal="true"
            aria-label={label}
            onClick={(e) => e.stopPropagation()}
            initial={{ opacity: 0, scale: 0.96, y: 10 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.97, y: 8 }}
            transition={{ duration: 0.22, ease: [0.22, 0.61, 0.36, 1] }}
            className={cn(
              'relative max-h-[90vh] w-full overflow-y-auto rounded-3xl border border-brand-text/10 bg-brand-surface shadow-glass outline-none',
              size === 'xl' ? 'max-w-4xl' : 'max-w-2xl',
              className,
            )}
          >
            <button
              onClick={onClose}
              aria-label="Fechar"
              className="absolute right-4 top-4 z-10 grid h-9 w-9 place-items-center rounded-full border border-brand-text/10 bg-brand-surface/90 text-brand-text transition-colors hover:border-brand-neon/40 hover:text-brand-neon"
            >
              <X className="h-4 w-4" />
            </button>
            {children}
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

// apps/imobia/frontend/src/components/Modal.vue
<script setup>
import { nextTick, ref, useId, watch } from 'vue';

const props = defineProps({ title: String, open: Boolean });
const emit = defineEmits(['close']);

const titleId = useId();
const card = ref(null);
let lastActive = null;

const FOCUSABLE = 'a[href], button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])';

function focusables(root) {
  if (!root) return [];
  return Array.from(root.querySelectorAll(FOCUSABLE)).filter((el) => el.offsetParent !== null);
}

function initialTarget() {
  const body = card.value?.querySelector('.md-body');
  const inBody = focusables(body);
  if (inBody.length) return inBody[0];
  return focusables(card.value)[0] || card.value;
}

function onKeydown(e) {
  if (e.key === 'Escape') { e.preventDefault(); emit('close'); return; }
  if (e.key !== 'Tab') return;
  const f = focusables(card.value);
  if (!f.length) { e.preventDefault(); card.value?.focus(); return; }
  const first = f[0];
  const last = f[f.length - 1];
  const active = document.activeElement;
  const outside = !card.value.contains(active);
  if (e.shiftKey && (active === first || outside)) { e.preventDefault(); last.focus(); }
  else if (!e.shiftKey && (active === last || outside)) { e.preventDefault(); first.focus(); }
}

watch(() => props.open, (isOpen) => {
  if (isOpen) {
    lastActive = document.activeElement;
    nextTick(() => { initialTarget()?.focus(); });
  } else if (lastActive) {
    lastActive.focus?.();
    lastActive = null;
  }
});
</script>
<template>
  <Teleport to="body">
    <div v-if="open" class="md-overlay" @click.self="emit('close')">
      <div
        ref="card"
        class="md-card"
        role="dialog"
        aria-modal="true"
        :aria-labelledby="titleId"
        tabindex="-1"
        @keydown="onKeydown"
      >
        <div class="md-head">
          <h3 :id="titleId">{{ title }}</h3>
          <button class="md-x" @click="emit('close')" aria-label="fechar">✕</button>
        </div>
        <div class="md-body"><slot /></div>
        <div v-if="$slots.footer" class="md-foot"><slot name="footer" /></div>
      </div>
    </div>
  </Teleport>
</template>
<style scoped>
.md-overlay { position: fixed; inset: 0; background: rgba(0,0,0,0.6); display: flex; align-items: flex-start; justify-content: center; padding: 6vh 16px; z-index: 60; backdrop-filter: blur(3px); overflow-y: auto; }
.md-card { width: 100%; max-width: 560px; background: var(--im-surface); border: 1px solid var(--im-border); border-radius: 16px; box-shadow: var(--im-shadow); }
.md-card:focus { outline: none; }
.md-head { display: flex; align-items: center; justify-content: space-between; padding: 16px 20px; border-bottom: 1px solid var(--im-border); }
.md-head h3 { margin: 0; font-size: 17px; }
.md-x { background: none; border: none; color: var(--im-muted); font-size: 16px; cursor: pointer; }
.md-x:hover { color: var(--im-text); }
.md-x:focus-visible { outline: 2px solid var(--im-accent); outline-offset: 2px; border-radius: 6px; }
.md-body { padding: 20px; }
.md-foot { padding: 14px 20px; border-top: 1px solid var(--im-border); display: flex; justify-content: flex-end; gap: 10px; }
</style>
